### GET/
GET http://localhost:5000

### Register the user POST/AUTH/register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "ethan@gmail.com",
    "password": "123456789"
}

### Login the user POST/AUTH/login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "ethan@gmail.com",
    "password": "123456789"
}